# Generated by Django 2.1 on 2018-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('testcase1', models.CharField(max_length=126)),
                ('testcase2', models.CharField(max_length=126)),
                ('testcase4', models.CharField(max_length=126)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
