# Generated by Django 2.1 on 2018-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180815_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='questions',
            field=models.ManyToManyField(to='basic_app.Questions'),
        ),
    ]
