# Generated by Django 2.1 on 2018-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_userprofileinfo_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='counter',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
