# Generated by Django 2.1 on 2018-08-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_remove_userprofileinfo_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='questions',
        ),
    ]
