# Generated by Django 2.1 on 2018-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_remove_userprofileinfo_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='testcase1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='testcase2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='testcase4',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='rank',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='quest1test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='quest2test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='quest3test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='quest4test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='quest5test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='quest6test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='totaltest',
            field=models.IntegerField(default=0),
        ),
    ]
