# Generated by Django 2.1 on 2018-08-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_remove_userprofileinfo_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='quest1test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='quest2test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='quest3test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='quest4test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='quest5test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='quest6test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='totaltest',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
